### ISSUE TITLE
Front pages as SPA

### ISSUE THREAD

**Issue by dany-eudes** [darryldecode/laravel-starter-kit#10]
What changes would you recommend for us if we also want the SPA on the front pages?
The procedure appears to be to duplicate the `SinglePageController` to have one for the front pages. Also adapt `front.blade.php` to be more like `admin.blade.php`. Write the routes on the `web.php` as are the routes of admin. What would really be a good practice? Could you please provide us with a little guide?

**Comment by darryldecode** [comment]
hello @dany-eudes , yes most of what you are thinking are correct. I will give you a guide on how I would do it on my part but that does not mean it's the best as there is always many ways to do things and it depends on your requirements and preference. But here is my advice.

- create SinglePageController under Http/Front and extend the abstract FrontController
- on resources/js folder, create a front folder which will contain js files or vue components and vue routes for front SPA ( most of the time, you will just copy paste the admin.js and route.js and rename the admin,js to front.js and udpate things accordingly. The routes also, update accordingly )
- Write the rotes on web.php as are the routes of admin but update accordingly
- you would also need to update webpack.,mix.js to add the new paths to be invcluded and compile. you will see for admin, it produces admin.js, for front SPA should also have front.js produce. This way we have clear separation of things and js codes are minimal because only codes for front is loaded on front and only codes for admin is loaded on admin.

So to wrap up, most of it is dupicate what is the admin setup but update accordingly and that you also know what those things do. Happy coding!

**Comment by darryldecode** [comment]
@dany-eudes i would also suggest if it is the intention for user dashboard or client facing dashboard, do the same but use the "user" instead of "front" since the front was intended for web pages or public pages. But if the intention is to make the public pages in SPA, then that is correct.

**Comment by dany-eudes** [comment]
@darryldecode, thank you so much for you quick reply. I'll try to follow your suggestions. 
Laravel embrace Vue.js for their view tool and I think your started kit is a thin base code to (really) start happy coding.
Maybe others will get you recommendations too. See ya!
