### ISSUE TITLE
Pagination issue

### ISSUE THREAD

**Issue by akramwahid** [darryldecode/laravel-starter-kit#8]
hi, when i set pagination to "all", it doesn't work

**Comment by darryldecode** [comment]
Hi @akramwahid thanks for reporting. Should be fixed now https://github.com/darryldecode/laravel-starter-kit/commit/32585532b8245e74460ab392ac58e5e7effd4f71

**Comment by darryldecode** [comment]
@akramwahid you can supply it as parameters. Not actually hard coded. There is a parameter if you don't want a paginated format, you pass paginate = "no" .. that will return non paginated structure. The only purpose I included it was because some UI like on vuetify data tables, when we choose ALL, it will pass a per_page value of -1, so I need to handle that on backend as well. Here is the updated code, see https://github.com/darryldecode/laravel-starter-kit/blob/844ddc2c993a045dc609002b386216fc5de8d090/app/Components/Core/BaseRepository.php#L46

**Comment by darryldecode** [comment]
If there is better way to do this w/o the need to change any code on frontend UI, please feel free to do a PR :)
